services:
  - type: web
    name: whatsapp-userbot
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SESSION
        value: RGNK~Lc6A01FN
      - key: API_KEY
        value: rnd_E7kUr5ImWfGKuWuwBkil0z7Sckjv
